[test]
coverageThreshold = { lines = 0.90, functions = 0.90 }
coveragePathIgnorePatterns = [
  "node_modules",
  "*.test.ts",
  "dist",
  "fixtures",
  "**/src/testing/**",
  "**/private/var/folders/**",
  "**/var/folders/**",
]

